# MODEL - documents
# SQLAlchemy model for the documents table
from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    String,
    UniqueConstraint,
    Uuid,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


# Metadata of a file attached to a building. The file itself lives in the
# storage (disk or bucket) under storage_key; this table never holds its bytes.
class Document(Base):
    __tablename__ = "documents"

    __table_args__ = (
        CheckConstraint(
            "kind IN ('PLAN', 'REPORT', 'INVOICE', 'PHOTO', 'OTHER')",
            name="ck_documents_kind",
        ),
        CheckConstraint(
            "size >= 0",
            name="ck_documents_size",
        ),
        # Two rows pointing to the same file would delete each other's file.
        UniqueConstraint("storage_key", name="uq_documents_storage_key"),
        # Listing of a building, newest first.
        Index("ix_documents_site_created_at", "site_id", "created_at"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
    )

    # Same organization as the site. Stored too so the tenant filter does not
    # need a join; the service takes it from the site, never from the request.
    organization_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey(
            "organizations.id",
            name="fk_documents_organization_id_organizations",
            ondelete="CASCADE",
        ),
        nullable=False,
    )

    # Deleting the building deletes its documents.
    site_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey(
            "sites.id",
            name="fk_documents_site_id_sites",
            ondelete="CASCADE",
        ),
        nullable=False,
    )

    # PLAN, REPORT, INVOICE, PHOTO or OTHER.
    kind: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
    )

    # Original name of the uploaded file, shown to the user.
    filename: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )

    # MIME type, for example "application/pdf". 255 = type + "/" + subtype
    # at their RFC 6838 maximum.
    content_type: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )

    # In bytes. BigInteger: a 2 GB file does not fit in Integer.
    size: Mapped[int] = mapped_column(
        BigInteger,
        nullable=False,
    )

    # Where the file is in the storage. Generated by the backend, never the
    # user's filename, so two "plano.pdf" do not collide.
    storage_key: Mapped[str] = mapped_column(
        String(512),
        nullable=False,
    )

    # Who uploaded it. NULL if that user was deleted: the document is kept.
    uploaded_by: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey(
            "users.id",
            name="fk_documents_uploaded_by_users",
            ondelete="SET NULL",
        ),
        nullable=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    # Document.site <-> Site.documents
    site: Mapped["Site"] = relationship(
        "Site",
        back_populates="documents",
    )
