"""empty message

Revision ID: 55dd704fd19b
Revises: d31341420683
Create Date: 2026-08-30 02:47:01.978321
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '55dd704fd19b'
down_revision: Union[str, Sequence[str], None] = 'd31341420683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
