"""fix alerts type/status check constraints, add message

Revision ID: b506173c2aac
Revises: 713aa912ec73
Create Date: 2026-09-18 22:32:58.893477
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'b506173c2aac'
down_revision: Union[str, Sequence[str], None] = '713aa912ec73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('message', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'message')
    # ### end Alembic commands ###
