"""create initial domain tables

Revision ID: d31341420683
Revises: 
Create Date: 2026-08-30 02:29:15.667652
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'd31341420683'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
